# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'Microsoft Internal Subscription 1(5648d12a-ba49-4789-8793-6f7cc54e1556)'
  
  # Environment name
  environmentName: 'demoangularmimott'

  # Web app name
  webAppName: 'demoangularmimott'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Install Node.js'

      - script: |
          npm install -g @angular/cli
          npm install
          ng build
        displayName: 'npm install and build'
        condition: 
      - task: Npm@1
        displayName: 'Install Angular app packages'
        inputs:
         command: 'ci'
      
      - task: Npm@1
        displayName: Build the app
        inputs:
         command: custom
         verbose: false
         customCommand: 'run build'
        
        # Archive the files after build from dist folder
      - task: ArchiveFiles@2
        displayName: Zip Angular dist folder
        inputs:
          rootFolderOrFile: 'dist/${{ parameters.AppName }}'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/${{ parameters.ProjectName }}.zip'
          replaceExistingArchive: true

      - task: PublishPipelineArtifact@1
        displayName: Publish Angular app dist folder artifact
        inputs:
           targetPath: '$(Build.ArtifactStagingDirectory)'
           artifactName: '${{ parameters.ProjectName }}'
           publishLocation: 'pipeline'